const dataDummyReservasi = [
  {
    id: "RSV001",
    namaCustomer: "John Doe",
    tanggalBooking: "2023-10-01",
    tanggalAcara: "2023-10-05",
    waktuAcara: "10:00",
    kategoriCustomer: "Umum",
    pilihanPaket: "Paket A",
    servisTambahan: "Dekorasi, Catering",
    pembayaran: "Sudah Dibayar",
    accTim: "Diterima",
    noWaPemesan: "08123456789",
  },
  {
    id: "RSV002",
    namaCustomer: "Jane Smith",
    tanggalBooking: "2023-10-02",
    tanggalAcara: "2023-10-07",
    waktuAcara: "14:30",
    kategoriCustomer: "Perusahaan",
    pilihanPaket: "Paket B",
    servisTambahan: "Catering, Musik",
    pembayaran: "Belum Dibayar",
    accTim: "Ditolak",
    noWaPemesan: "08123456790",
  },
  {
    id: "RSV003",
    namaCustomer: "Ahmad Yani",
    tanggalBooking: "2023-10-03",
    tanggalAcara: "2023-10-09",
    waktuAcara: "09:00",
    kategoriCustomer: "Umum",
    pilihanPaket: "Paket C",
    servisTambahan: "Dekorasi",
    pembayaran: "Sudah Dibayar",
    accTim: "Diterima",
    noWaPemesan: "08123456791",
  },
  {
    id: "RSV004",
    namaCustomer: "Siti Aminah",
    tanggalBooking: "2023-10-04",
    tanggalAcara: "2023-10-10",
    waktuAcara: "13:00",
    kategoriCustomer: "Perusahaan",
    pilihanPaket: "Paket A",
    servisTambahan: "Catering",
    pembayaran: "Belum Dibayar",
    accTim: "Dalam Proses",
    noWaPemesan: "08123456792",
  },
  {
    id: "RSV005",
    namaCustomer: "Budi Santoso",
    tanggalBooking: "2023-10-05",
    tanggalAcara: "2023-10-12",
    waktuAcara: "15:00",
    kategoriCustomer: "Umum",
    pilihanPaket: "Paket B",
    servisTambahan: "Dekorasi, Musik",
    pembayaran: "Sudah Dibayar",
    accTim: "Diterima",
    noWaPemesan: "08123456793",
  },
  {
    id: "RSV006",
    namaCustomer: "Rina Sari",
    tanggalBooking: "2023-10-06",
    tanggalAcara: "2023-10-13",
    waktuAcara: "11:00",
    kategoriCustomer: "Perusahaan",
    pilihanPaket: "Paket C",
    servisTambahan: "Catering, Dekorasi",
    pembayaran: "Belum Dibayar",
    accTim: "Ditolak",
    noWaPemesan: "08123456794",
  },
  {
    id: "RSV007",
    namaCustomer: "Dedi Kusuma",
    tanggalBooking: "2023-10-07",
    tanggalAcara: "2023-10-14",
    waktuAcara: "16:00",
    kategoriCustomer: "Umum",
    pilihanPaket: "Paket A",
    servisTambahan: "Musik",
    pembayaran: "Sudah Dibayar",
    accTim: "Diterima",
    noWaPemesan: "08123456795",
  },
  {
    id: "RSV008",
    namaCustomer: "Lina Putri",
    tanggalBooking: "2023-10-08",
    tanggalAcara: "2023-10-15",
    waktuAcara: "12:00",
    kategoriCustomer: "Perusahaan",
    pilihanPaket: "Paket B",
    servisTambahan: "Dekorasi, Catering",
    pembayaran: "Belum Dibayar",
    accTim: "Dalam Proses",
    noWaPemesan: "08123456796",
  },
  {
    id: "RSV009",
    namaCustomer: "Hendra Wijaya",
    tanggalBooking: "2023-10-09",
    tanggalAcara: "2023-10-16",
    waktuAcara: "10:30",
    kategoriCustomer: "Umum",
    pilihanPaket: "Paket C",
    servisTambahan: "Catering",
    pembayaran: "Sudah Dibayar",
    accTim: "Diterima",
    noWaPemesan: "08123456797",
  },
  {
    id: "RSV010",
    namaCustomer: "Maya Lestari",
    tanggalBooking: "2023-10-10",
    tanggalAcara: "2023-10-17",
    waktuAcara: "14:00",
    kategoriCustomer: "Perusahaan",
    pilihanPaket: "Paket A",
    servisTambahan: "Dekorasi, Musik",
    pembayaran: "Belum Dibayar",
    accTim: "Ditolak",
    noWaPemesan: "08123456798",
  },
  {
    id: "RSV011",
    namaCustomer: "Rudi Hartono",
    tanggalBooking: "2023-10-11",
    tanggalAcara: "2023-10-18",
    waktuAcara: "09:30",
    kategoriCustomer: "Umum",
    pilihanPaket: "Paket B",
    servisTambahan: "Catering",
    pembayaran: "Sudah Dibayar",
    accTim: "Diterima",
    noWaPemesan: "08123456799",
  },
  {
    id: "RSV012",
    namaCustomer: "Tina Melinda",
    tanggalBooking: "2023-10-12",
    tanggalAcara: "2023-10-19",
    waktuAcara: "13:30",
    kategoriCustomer: "Perusahaan",
    pilihanPaket: "Paket C",
    servisTambahan: "Dekorasi",
    pembayaran: "Belum Dibayar",
    accTim: "Dalam Proses",
    noWaPemesan: "08123456800",
  },
  {
    id: "RSV013",
    namaCustomer: "Arif Rahman",
    tanggalBooking: "2023-10-13",
    tanggalAcara: "2023-10-20",
    waktuAcara: "15:30",
    kategoriCustomer: "Umum",
    pilihanPaket: "Paket A",
    servisTambahan: "Musik, Catering",
    pembayaran: "Sudah Dibayar",
    accTim: "Diterima",
    noWaPemesan: "08123456801",
  },
  {
    id: "RSV014",
    namaCustomer: "Sri Wulan",
    tanggalBooking: "2023-10-14",
    tanggalAcara: "2023-10-21",
    waktuAcara: "11:30",
    kategoriCustomer: "Perusahaan",
    pilihanPaket: "Paket B",
    servisTambahan: "Dekorasi",
    pembayaran: "Belum Dibayar",
    accTim: "Ditolak",
    noWaPemesan: "08123456802",
  },
  {
    id: "RSV015",
    namaCustomer: "Eko Prasetyo",
    tanggalBooking: "2023-10-15",
    tanggalAcara: "2023-10-22",
    waktuAcara: "16:30",
    kategoriCustomer: "Umum",
    pilihanPaket: "Paket C",
    servisTambahan: "Catering, Musik",
    pembayaran: "Sudah Dibayar",
    accTim: "Diterima",
    noWaPemesan: "08123456803",
  },
];

export default dataDummyReservasi;