import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./component/navbar";
import Footer from "./component/footer";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const fontBody = Poppins({
	variable: "--font-body",
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) 

{
	const location = typeof window !== "undefined" ? window.location : { pathname: "/" };
	const path = ["/", "/admin", "/dashboard", "/login", "/register"];
	return (
		<html lang="en">
			<body className={`${fontBody.className} antialiased`}>
				{!path.includes(location.pathname) && <Navbar />}
				{children}
				{!path.includes(location.pathname) && <Footer />}
			
			</body>
		</html>
	);
}
